services:
  - type: web
    name: finrelief-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

  - type: static
    name: finrelief-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist

    envVars:
      - key: VITE_API_URL
        value: https://finreliief2.onrender.com